// Site-wide JS enhancements. The nav, footer, and skip link are static HTML
// generated by tools/sync_chrome.py (edit the chrome there, then re-run it);
// this file only adds behavior that genuinely needs JavaScript: the back-to-
// top button, the mobile nav menu, scroll reveals, card tilt, and the video
// lightbox.
(function () {
    var TOP_SVG = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="18 15 12 9 6 15"></polyline></svg>';

    // Mobile morphing-pill nav: the Menu button (hidden on desktop) expands
    // the pill into a dropdown card. All the visuals live in responsive.css
    // under nav.is-open; this only manages state, label, and scroll lock.
    function initNavMenu() {
        var nav = document.querySelector('nav[aria-label="Primary navigation"]');
        var btn = document.getElementById('nav-menu-btn');
        if (!nav || !btn) return;
        var label = document.getElementById('nav-menu-label');

        function setOpen(open) {
            nav.classList.toggle('is-open', open);
            document.documentElement.classList.toggle('nav-open', open);
            btn.setAttribute('aria-expanded', String(open));
            if (label) label.textContent = open ? 'Close' : 'Menu';
        }

        window.toggleNavMenu = function () {
            setOpen(!nav.classList.contains('is-open'));
        };

        document.addEventListener('keydown', function (event) {
            if (event.key === 'Escape' && nav.classList.contains('is-open')) {
                setOpen(false);
                btn.focus();
            }
        });
        // A tap on any link closes the menu; mostly relevant for the rare
        // same-page navigation, since a real navigation resets everything.
        nav.querySelector('.nav-links').addEventListener('click', function (event) {
            if (event.target.closest('a')) setOpen(false);
        });
        // Crossing back to the desktop layout must never leave the body
        // scroll-locked by a menu that no longer exists.
        window.matchMedia('(min-width: 769px)').addEventListener('change', function (event) {
            if (event.matches) setOpen(false);
        });
    }

    // Scroll reveal: both selectors must mirror the :is() list in base.css,
    // or an element would start hidden that no observer ever reveals.
    // Children of a stagger container reveal together, offset by index,
    // when the container enters the viewport.
    var REVEAL_SELECTOR = '.page-hero, .section-header, .hero-card, .glass-card, .section-cta, .cta-section, .code-cta, .carousel-container, .coming-soon, .article-backbar, .article-wrap';
    var STAGGER_SELECTOR = '.featured-grid, .bento-grid';

    function initReveal() {
        function showNow(el) { el.classList.add('in-view'); }

        // The reveal transition is inline (not a CSS class) so the
        // element's stylesheet transitions, e.g. the card hover lift,
        // come back untouched once the reveal has finished.
        function reveal(el, delay) {
            setTimeout(function () {
                el.style.transition = 'opacity 0.65s ease, transform 0.65s cubic-bezier(0.2, 0.8, 0.2, 1)';
                el.classList.add('in-view');
                setTimeout(function () { el.style.transition = ''; }, 700);
            }, delay);
        }

        // groups: [element to watch, elements revealed (staggered) when it shows]
        var groups = [];
        document.querySelectorAll(STAGGER_SELECTOR).forEach(function (grid) {
            groups.push([grid, Array.prototype.slice.call(grid.children)]);
        });
        document.querySelectorAll(REVEAL_SELECTOR).forEach(function (el) {
            if (el.closest(STAGGER_SELECTOR)) return; // revealed with its grid
            groups.push([el, [el]]);
        });

        if (window.matchMedia('(prefers-reduced-motion: reduce)').matches ||
            !('IntersectionObserver' in window)) {
            groups.forEach(function (group) { group[1].forEach(showNow); });
            return;
        }

        var byTarget = new Map();
        var observer = new IntersectionObserver(function (entries) {
            entries.forEach(function (entry) {
                if (!entry.isIntersecting) return;
                observer.unobserve(entry.target);
                byTarget.get(entry.target).forEach(function (el, i) {
                    reveal(el, i * 90);
                });
            });
        }, { rootMargin: '0px 0px -8% 0px' });

        groups.forEach(function (group) {
            // Elements that start display:none (the contact form's success
            // panel) never intersect; mark them revealed now so they're
            // fully visible whenever other code shows them.
            if (getComputedStyle(group[0]).display === 'none') {
                group[1].forEach(showNow);
                return;
            }
            byTarget.set(group[0], group[1]);
            observer.observe(group[0]);
        });
    }

    // Pointer tilt: [data-tilt] cards face the cursor (hover-capable,
    // fine-pointer devices only): the edge under the pointer lifts toward
    // the viewer, so the card's face turns to follow the mouse. Signs
    // matter here: rotateX(+) brings the BOTTOM edge forward and
    // rotateY(+) pushes the RIGHT edge back, hence +dy and -dx. The
    // inline transform overrides the CSS hover lift while the pointer is
    // over the card and is cleared on leave, handing back to the
    // stylesheet.
    function initTilt() {
        if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
        if (!window.matchMedia('(hover: hover) and (pointer: fine)').matches) return;
        var MAX_DEG = 5;
        document.querySelectorAll('[data-tilt]').forEach(function (card) {
            var frame = null;
            var lastEvent = null;
            card.addEventListener('pointermove', function (event) {
                lastEvent = event;
                if (frame) return;
                frame = requestAnimationFrame(function () {
                    frame = null;
                    var rect = card.getBoundingClientRect();
                    var dx = (lastEvent.clientX - rect.left) / rect.width - 0.5;
                    var dy = (lastEvent.clientY - rect.top) / rect.height - 0.5;
                    card.style.transform =
                        'perspective(900px) translateY(-6px)' +
                        ' rotateX(' + (dy * MAX_DEG).toFixed(2) + 'deg)' +
                        ' rotateY(' + (-dx * MAX_DEG).toFixed(2) + 'deg)';
                });
            });
            card.addEventListener('pointerleave', function () {
                if (frame) { cancelAnimationFrame(frame); frame = null; }
                card.style.transform = '';
            });
        });
    }

    function addBackToTop() {
        var btn = document.createElement('button');
        btn.id = 'back-to-top';
        btn.setAttribute('aria-label', 'Back to top');
        btn.title = 'Back to top';
        btn.innerHTML = TOP_SVG;
        document.body.appendChild(btn);
        window.addEventListener('scroll', function () {
            btn.classList.toggle('visible', window.scrollY > 300);
        }, { passive: true });
        btn.addEventListener('click', function () {
            window.scrollTo({ top: 0, behavior: 'smooth' });
        });
    }

    // Autoplaying demo videos should hold still for reduced-motion users.
    function respectReducedMotion() {
        if (!window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
        document.querySelectorAll('video[autoplay]').forEach(function (v) {
            v.removeAttribute('autoplay');
            v.pause();
        });
    }

    function init() {
        initNavMenu();
        initReveal();
        initTilt();
        addBackToTop();
        respectReducedMotion();
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
})();

// Demo video that doesn't sit inside a cropped card preview (e.g. the
// KanaCard case study): clicking just toggles play/pause, since the
// full picture is already visible at its natural aspect ratio.
window.toggleCardVideo = function (event, wrap) {
    event.preventDefault();
    event.stopPropagation();
    var video = wrap.querySelector('video');
    if (!video) return;
    if (video.paused) {
        video.play();
    } else {
        video.pause();
    }
};

// Full-video lightbox: for card previews that crop a portrait recording
// to fit a grid cell (e.g. the homepage Rogue Roll card), clicking opens
// an overlay with the uncropped video at its natural aspect ratio. The
// overlay is a fixed-position layer built once and reused, so opening it
// never touches the surrounding grid's layout or the other cards' size.
(function () {
    var modal, modalVideo, opener;

    function build() {
        if (modal) return;
        modal = document.createElement('div');
        modal.className = 'video-modal';
        modal.setAttribute('role', 'dialog');
        modal.setAttribute('aria-modal', 'true');
        modal.innerHTML =
            '<button type="button" class="video-modal-close" aria-label="Close video">' +
            '<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>' +
            '</button>' +
            '<video class="video-modal-video" controls loop playsinline></video>';
        modal.addEventListener('click', function (event) {
            if (event.target === modal) close();
        });
        // aria-modal promises focus stays inside; keep Tab cycling between
        // the close button and the video's native controls.
        modal.addEventListener('keydown', function (event) {
            if (event.key !== 'Tab') return;
            var focusables = modal.querySelectorAll('button, video');
            var first = focusables[0];
            var last = focusables[focusables.length - 1];
            if (event.shiftKey && document.activeElement === first) {
                event.preventDefault();
                last.focus();
            } else if (!event.shiftKey && document.activeElement === last) {
                event.preventDefault();
                first.focus();
            }
        });
        modal.querySelector('.video-modal-close').addEventListener('click', close);
        document.body.appendChild(modal);
        modalVideo = modal.querySelector('video');
    }

    function close() {
        if (!modal) return;
        modal.classList.remove('is-open');
        document.documentElement.classList.remove('video-modal-open');
        modalVideo.pause();
        // Hand focus back to the button that launched the lightbox.
        if (opener && document.contains(opener)) opener.focus();
        opener = null;
    }

    document.addEventListener('keydown', function (event) {
        if (event.key === 'Escape' && modal && modal.classList.contains('is-open')) close();
    });

    window.openVideoModal = function (event, src, label, poster) {
        event.preventDefault();
        event.stopPropagation();
        build();
        opener = event.currentTarget || document.activeElement;
        modalVideo.src = src;
        modalVideo.poster = poster || '';
        modalVideo.setAttribute('aria-label', label || 'Demo video');
        modal.setAttribute('aria-label', label || 'Demo video');
        modal.classList.add('is-open');
        document.documentElement.classList.add('video-modal-open');
        modalVideo.currentTime = 0;
        modalVideo.play();
        modal.querySelector('.video-modal-close').focus();
    };
})();

// Command Palette (Cmd + K) implementation
(function () {
    var palette, input, list, selectedIndex = 0, items = [];

    var SEARCH_DATA = [
        { title: 'Home', category: 'Page', url: 'index.html', icon: '🏠' },
        { title: 'Projects', category: 'Page', url: 'projects.html', icon: '🚀' },
        { title: 'Apps Catalog', category: 'Page', url: 'apps.html', icon: '📱' },
        { title: 'About Me', category: 'Page', url: 'about.html', icon: '👤' },
        { title: 'Resume', category: 'Page', url: 'resume.html', icon: '📄' },
        { title: 'Blog', category: 'Page', url: 'blog.html', icon: '✍️' },
        { title: 'Contact', category: 'Page', url: 'contact.html', icon: '✉️' },
        { title: 'Uses & Gear', category: 'Page', url: 'uses.html', icon: '💻' },
        { title: 'KanaCard', category: 'App', url: 'kanacard.html', icon: '🎴' },
        { title: 'Rogue Roll', category: 'App', url: 'https://apps.apple.com/us/app/rogue-roll-dice-deck-builder/id6757452802', target: '_blank', icon: '🎲' },
        { title: 'Stock Market Sim', category: 'App', url: 'https://apps.apple.com/us/app/stock-market-sim/id6511208338', target: '_blank', icon: '📈' },
        { title: 'Kodou', category: 'App', url: 'https://apps.apple.com/us/app/kodou-memory-grid-game/id6753267966', target: '_blank', icon: '🎵' },
        { title: 'Type Kana', category: 'App', url: 'https://apps.apple.com/us/app/type-kana/id6574367514', target: '_blank', icon: '⌨️' },
        { title: 'Wordly', category: 'App', url: 'https://apps.apple.com/us/app/wordly-puzzle-game-solver/id6740254685', target: '_blank', icon: '🧩' },
        { title: 'Idea Vault', category: 'App', url: 'https://apps.apple.com/us/app/idea-vault-notes-journal/id6572281488', target: '_blank', icon: '💡' },
        { title: 'Toggle Light / Dark Mode', category: 'Action', action: function () { toggleTheme(); }, icon: '🌓' },
        { title: 'Download Resume (PDF)', category: 'Action', url: 'Resume.pdf', target: '_blank', icon: '📥' }
    ];

    function buildPalette() {
        if (palette) return;
        palette = document.createElement('div');
        palette.className = 'cmd-palette';
        palette.setAttribute('role', 'dialog');
        palette.setAttribute('aria-modal', 'true');
        palette.setAttribute('aria-label', 'Command Palette');

        palette.innerHTML =
            '<div class="cmd-palette-card">' +
            '  <div class="cmd-palette-input-wrap">' +
            '    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>' +
            '    <input type="text" class="cmd-palette-input" placeholder="Type a command or search pages & apps..." aria-label="Search command palette" role="combobox" aria-autocomplete="list" aria-expanded="false" aria-controls="cmd-palette-listbox" aria-activedescendant="">' +
            '  </div>' +
            '  <ul class="cmd-palette-list" id="cmd-palette-listbox" role="listbox"></ul>' +
            '  <div class="cmd-palette-footer">' +
            '    <span>Search portfolio &amp; apps</span>' +
            '    <div class="cmd-palette-keys">' +
            '      <span><span class="cmd-key">↑</span> <span class="cmd-key">↓</span> Navigate</span>' +
            '      <span><span class="cmd-key">↵</span> Select</span>' +
            '      <span><span class="cmd-key">ESC</span> Close</span>' +
            '    </div>' +
            '  </div>' +
            '</div>';

        document.body.appendChild(palette);
        input = palette.querySelector('.cmd-palette-input');
        list = palette.querySelector('.cmd-palette-list');

        palette.addEventListener('click', function (e) {
            if (e.target === palette) closeCmdPalette();
        });

        input.addEventListener('input', function () { renderList(input.value); });

        palette.addEventListener('keydown', function (e) {
            if (e.key === 'Escape') {
                closeCmdPalette();
            } else if (e.key === 'ArrowDown') {
                e.preventDefault();
                setSelection(selectedIndex + 1);
            } else if (e.key === 'ArrowUp') {
                e.preventDefault();
                setSelection(selectedIndex - 1);
            } else if (e.key === 'Enter') {
                e.preventDefault();
                executeSelected();
            } else if (e.key === 'Tab') {
                // The input is the only focusable element in the dialog; block
                // Tab so focus can't leak past the backdrop to the page behind.
                e.preventDefault();
            }
        });
    }

    function renderList(query) {
        var q = (query || '').toLowerCase().trim();
        items = SEARCH_DATA.filter(function (item) {
            return !q || item.title.toLowerCase().indexOf(q) !== -1 || item.category.toLowerCase().indexOf(q) !== -1;
        });

        list.innerHTML = '';
        if (items.length === 0) {
            list.innerHTML = '<li style="padding: 20px; text-align: center; color: var(--text-muted);">No matching commands or pages found</li>';
            input.setAttribute('aria-activedescendant', '');
            return;
        }

        items.forEach(function (item, index) {
            var li = document.createElement('li');
            li.id = 'cmd-palette-option-' + index;
            li.setAttribute('role', 'option');
            li.setAttribute('aria-selected', index === 0 ? 'true' : 'false');
            li.className = 'cmd-palette-item' + (index === 0 ? ' is-selected' : '');
            li.innerHTML =
                '<div class="cmd-palette-item-left">' +
                '  <span>' + item.icon + '</span>' +
                '  <span>' + item.title + '</span>' +
                '</div>' +
                '<span class="cmd-palette-item-category">' + item.category + '</span>';

            li.addEventListener('click', function () {
                selectedIndex = index;
                executeSelected();
            });
            list.appendChild(li);
        });
        selectedIndex = 0;
        input.setAttribute('aria-activedescendant', 'cmd-palette-option-0');
    }

    function setSelection(index) {
        var childNodes = list.querySelectorAll('.cmd-palette-item');
        if (!childNodes.length) return;
        if (index < 0) index = childNodes.length - 1;
        if (index >= childNodes.length) index = 0;

        if (childNodes[selectedIndex]) {
            childNodes[selectedIndex].classList.remove('is-selected');
            childNodes[selectedIndex].setAttribute('aria-selected', 'false');
        }
        selectedIndex = index;
        if (childNodes[selectedIndex]) {
            childNodes[selectedIndex].classList.add('is-selected');
            childNodes[selectedIndex].setAttribute('aria-selected', 'true');
            childNodes[selectedIndex].scrollIntoView({ block: 'nearest' });
            input.setAttribute('aria-activedescendant', childNodes[selectedIndex].id);
        }
    }

    function executeSelected() {
        var item = items[selectedIndex];
        if (!item) return;
        closeCmdPalette();
        if (item.action) {
            item.action();
        } else if (item.url) {
            if (item.target === '_blank') {
                window.open(item.url, '_blank', 'noopener,noreferrer');
            } else {
                window.location.href = item.url;
            }
        }
    }

    window.toggleCmdPalette = function () {
        buildPalette();
        var open = !palette.classList.contains('is-open');
        if (open) {
            palette.classList.add('is-open');
            input.setAttribute('aria-expanded', 'true');
            renderList('');
            input.value = '';
            setTimeout(function () { input.focus(); }, 50);
        } else {
            closeCmdPalette();
        }
    };

    function closeCmdPalette() {
        if (palette) palette.classList.remove('is-open');
        if (input) input.setAttribute('aria-expanded', 'false');
        var trigger = document.getElementById('cmd-k-btn');
        if (trigger) trigger.focus();
    }

    document.addEventListener('keydown', function (e) {
        if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'k') {
            e.preventDefault();
            window.toggleCmdPalette();
        }
    });
})();

// Animated Numbers Ticker for App Metrics
(function () {
    function animateCounters() {
        var elements = document.querySelectorAll('.app-downloads, .rating-num');
        if (!('IntersectionObserver' in window)) return;

        var observer = new IntersectionObserver(function (entries) {
            entries.forEach(function (entry) {
                if (entry.isIntersecting) {
                    observer.unobserve(entry.target);
                    var el = entry.target;
                    var text = el.textContent;
                    var match = text.match(/([0-9.]+)/);
                    if (!match) return;
                    var targetNum = parseFloat(match[1]);
                    if (isNaN(targetNum)) return;
                    var duration = 1000;
                    var startTime = null;

                    function step(timestamp) {
                        if (!startTime) startTime = timestamp;
                        var progress = Math.min((timestamp - startTime) / duration, 1);
                        var decimalPlaces = (match[1].indexOf('.') !== -1) ? match[1].split('.')[1].length : 0;
                        var current = (progress * targetNum).toFixed(decimalPlaces);
                        el.textContent = text.replace(match[1], current);
                        if (progress < 1) requestAnimationFrame(step);
                    }
                    requestAnimationFrame(step);
                }
            });
        }, { threshold: 0.5 });

        elements.forEach(function (el) { observer.observe(el); });
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', animateCounters);
    } else {
        animateCounters();
    }
})();
