// Site-wide JS enhancements. The nav, footer, and skip link are static HTML
// generated by tools/sync_chrome.py (edit the chrome there, then re-run it);
// this file only adds behavior that genuinely needs JavaScript.
(function () {
    var TOP_SVG = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="18 15 12 9 6 15"></polyline></svg>';

    function addBackToTop() {
        var btn = document.createElement('button');
        btn.id = 'back-to-top';
        btn.setAttribute('aria-label', 'Back to top');
        btn.title = 'Back to top';
        btn.innerHTML = TOP_SVG;
        document.body.appendChild(btn);
        window.addEventListener('scroll', function () {
            btn.classList.toggle('visible', window.scrollY > 300);
        }, { passive: true });
        btn.addEventListener('click', function () {
            window.scrollTo({ top: 0, behavior: 'smooth' });
        });
    }

    // Autoplaying demo videos should hold still for reduced-motion users.
    function respectReducedMotion() {
        if (!window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
        document.querySelectorAll('video[autoplay]').forEach(function (v) {
            v.removeAttribute('autoplay');
            v.pause();
        });
    }

    function init() {
        addBackToTop();
        respectReducedMotion();
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
})();

// Demo video that doesn't sit inside a cropped card preview (e.g. the
// KanaCard case study): clicking just toggles play/pause, since the
// full picture is already visible at its natural aspect ratio.
window.toggleCardVideo = function (event, wrap) {
    event.preventDefault();
    event.stopPropagation();
    var video = wrap.querySelector('video');
    if (!video) return;
    if (video.paused) {
        video.play();
    } else {
        video.pause();
    }
};

// Full-video lightbox: for card previews that crop a portrait recording
// to fit a grid cell (e.g. the homepage Rogue Roll card), clicking opens
// an overlay with the uncropped video at its natural aspect ratio. The
// overlay is a fixed-position layer built once and reused, so opening it
// never touches the surrounding grid's layout or the other cards' size.
(function () {
    var modal, modalVideo;

    function build() {
        if (modal) return;
        modal = document.createElement('div');
        modal.className = 'video-modal';
        modal.innerHTML =
            '<button type="button" class="video-modal-close" aria-label="Close video">' +
            '<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>' +
            '</button>' +
            '<video class="video-modal-video" controls loop playsinline></video>';
        modal.addEventListener('click', function (event) {
            if (event.target === modal) close();
        });
        modal.querySelector('.video-modal-close').addEventListener('click', close);
        document.body.appendChild(modal);
        modalVideo = modal.querySelector('video');
    }

    function close() {
        if (!modal) return;
        modal.classList.remove('is-open');
        document.body.classList.remove('video-modal-open');
        modalVideo.pause();
    }

    document.addEventListener('keydown', function (event) {
        if (event.key === 'Escape' && modal && modal.classList.contains('is-open')) close();
    });

    window.openVideoModal = function (event, src, label, poster) {
        event.preventDefault();
        event.stopPropagation();
        build();
        modalVideo.src = src;
        modalVideo.poster = poster || '';
        modalVideo.setAttribute('aria-label', label || 'Demo video');
        modal.classList.add('is-open');
        document.body.classList.add('video-modal-open');
        modalVideo.currentTime = 0;
        modalVideo.play();
    };
})();
