"""
Inline the shared site chrome (head boilerplate, skip link, nav, footer)
statically into every page, so the site works without JavaScript and the
header doesn't pop in after page load.

This script is the single source of truth for the shared <head> block (theme
colors, icons, stylesheet links in cascade order, script tags), the nav, and
the footer. After changing NAV_LINKS, CSS_PARTIALS, or anything else here,
re-run from the repo root:

    python3 tools/sync_chrome.py

It rewrites the blocks between the chrome markers in each *.html file
(idempotent; safe to run repeatedly), then stamps every local css/js URL
with a short content hash (?v=...) so a changed asset always gets a fresh
URL. Cloudflare fronts the site with a 4-hour browser cache, and without
the stamp a visitor can hold yesterday's stylesheet against today's HTML.
layout.js keeps only the behavior that genuinely needs JS (back-to-top
button, video lightbox).
"""
import glob
import hashlib
import os
import re

NAV_LINKS = [
    ("index.html", "Home"),
    ("projects.html", "Projects"),
    ("about.html", "About"),
    ("resume.html", "Resume"),
    ("contact.html", "Contact"),
    ("blog.html", "Blog"),
]

# Pages that should highlight a nav item other than themselves.
ACTIVE_ALIASES = {
    "apple-developer-fee.html": "blog.html",
    "kanacard.html": "projects.html",
    "apps.html": "projects.html",
}

# The footer carries two link columns: every site page (including Uses,
# which is footer-only personality content), then the app-facing utility
# pages that App Store listings, AdMob, and app users need to reach from
# anywhere.
FOOTER_SITE_LINKS = NAV_LINKS + [("uses.html", "Uses")]
FOOTER_APP_LINKS = [
    ("apps.html", "Apps"),
    ("support.html", "Support"),
    ("privacy.html", "Privacy"),
]

# 404.html is served at whatever URL the visitor requested, so its chrome
# URLs must be root-absolute. (Not <base href="/">: that would also rebase
# same-page #fragment links, sending the skip link to the homepage.)
URL_PREFIXES = {"404.html": "/"}

# Stylesheet partials, linked in cascade order (later files override earlier).
CSS_PARTIALS = ["base", "layout", "components", "pages", "utilities", "themes", "responsive"]

GITHUB_URL = "https://github.com/MWM1107"
LINKEDIN_URL = "https://www.linkedin.com/in/kevin-struna/"
APPSTORE_URL = "https://apps.apple.com/us/developer/kevin-struna/id1700293634"

GITHUB_SVG = '<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2A10 10 0 0 0 2 12C2 16.42 4.87 20.17 8.84 21.5C9.34 21.58 9.5 21.27 9.5 21C9.5 20.77 9.5 20.14 9.5 19.31C6.73 19.91 6.14 17.97 6.14 17.97C5.68 16.81 5.03 16.5 5.03 16.5C4.12 15.88 5.1 15.9 5.1 15.9C6.1 15.97 6.63 16.93 6.63 16.93C7.5 18.45 8.97 18 9.54 17.76C9.63 17.11 9.89 16.67 10.17 16.42C7.95 16.17 5.62 15.31 5.62 11.5C5.62 10.39 6 9.5 6.65 8.79C6.55 8.54 6.2 7.5 6.75 6.15C6.75 6.15 7.59 5.88 9.5 7.17C10.29 6.95 11.15 6.84 12 6.84C12.85 6.84 13.71 6.95 14.5 7.17C16.41 5.88 17.25 6.15 17.25 6.15C17.8 7.5 17.45 8.54 17.35 8.79C18 9.5 18.38 10.39 18.38 11.5C18.38 15.32 16.04 16.16 13.81 16.41C14.17 16.72 14.5 17.33 14.5 18.26C14.5 19.6 14.5 20.68 14.5 21C14.5 21.27 14.66 21.59 15.17 21.5C19.14 20.16 22 16.42 22 12A10 10 0 0 0 12 2Z"/></svg>'
LINKEDIN_SVG = '<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="currentColor"><path d="M19 3A2 2 0 0 1 21 5V19A2 2 0 0 1 19 21H5A2 2 0 0 1 3 19V5A2 2 0 0 1 5 3H19M18.5 18.5V13.2A3.26 3.26 0 0 0 15.24 9.94C14.39 9.94 13.4 10.46 12.92 11.24V10.13H10.13V18.5H12.92V13.57C12.92 12.8 13.54 12.17 14.31 12.17A1.4 1.4 0 0 1 15.71 13.57V18.5H18.5M6.88 8.56A1.68 1.68 0 0 0 8.56 6.88C8.56 5.95 7.81 5.19 6.88 5.19A1.69 1.69 0 0 0 5.19 6.88C5.19 7.81 5.95 8.56 6.88 8.56M8.27 18.5V10.13H5.5V18.5H8.27Z"/></svg>'
APPSTORE_SVG = '<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="currentColor"><path d="M18.71 19.5c-.83 1.24-1.71 2.45-3.05 2.47-1.34.03-1.77-.79-3.29-.79-1.53 0-2 .77-3.27.82-1.31.05-2.3-1.32-3.14-2.53C4.25 17 2.94 12.45 4.7 9.39c.87-1.52 2.43-2.48 4.12-2.51 1.28-.02 2.5.87 3.29.87.78 0 2.26-1.07 3.8-.91.65.03 2.47.26 3.64 1.98-.09.06-2.17 1.28-2.15 3.81.03 3.02 2.65 4.03 2.68 4.04-.03.07-.42 1.44-1.38 2.83zM13 3.5c.73-.83 1.94-1.46 2.94-1.5.13 1.17-.34 2.35-1.04 3.19-.69.85-1.83 1.51-2.95 1.42-.15-1.15.41-2.35 1.05-3.11z"/></svg>'

HEAD_START = "<!-- chrome:head (generated by tools/sync_chrome.py; edit there, then re-run) -->"
HEAD_END = "<!-- /chrome:head -->"
NAV_START = "<!-- chrome:nav (generated by tools/sync_chrome.py; edit there, then re-run) -->"
NAV_END = "<!-- /chrome:nav -->"
FOOT_START = "<!-- chrome:footer (generated by tools/sync_chrome.py; edit there, then re-run) -->"
FOOT_END = "<!-- /chrome:footer -->"

SKIP_LINK = '<a href="#main-content" class="skip-link">Skip to main content</a>'


def head_html(prefix):
    """Shared head boilerplate: theme colors, icons, styles, scripts."""
    lines = [
        # Address-bar color for mobile browsers; theme.js re-syncs these two
        # when a manual theme toggle overrides the OS preference.
        '<meta name="theme-color" content="#f5f5f7" media="(prefers-color-scheme: light)">',
        '<meta name="theme-color" content="#000000" media="(prefers-color-scheme: dark)">',
        '<link rel="icon" type="image/png" href="{0}img/favicon.png">'.format(prefix),
        '<link rel="apple-touch-icon" href="{0}img/favicon.png">'.format(prefix),
    ]
    lines += [
        '<link rel="stylesheet" href="{0}css/{1}.css">'.format(prefix, name)
        for name in CSS_PARTIALS
    ]
    lines += [
        # theme.js stays synchronous so data-theme is set before first paint.
        '<script src="{0}js/theme.js"></script>'.format(prefix),
        '<script src="{0}js/layout.js" defer></script>'.format(prefix),
    ]
    return "\n    ".join(lines)


def nav_html(page, prefix):
    active = ACTIVE_ALIASES.get(page, page)
    links = "".join(
        '<a href="{0}{1}"{3}>{2}</a>'.format(
            prefix, href, label, ' class="active"' if href == active else ""
        )
        for href, label in NAV_LINKS
    )
    # The menu button only exists visually on mobile, where the pill morphs
    # into a dropdown card (see layout.js toggleNavMenu). On desktop the
    # button is display:none and .nav-links is display:contents, so the
    # links lay out exactly as if they were direct children of <nav>.
    # Without JS the mobile menu can't open, so the collapsed state is
    # gated on the html.js class that theme.js sets: no JS, no collapse.
    return (
        '<nav aria-label="Primary navigation">'
        + '<button id="nav-menu-btn" class="nav-menu-btn" onclick="toggleNavMenu()"'
        + ' aria-expanded="false" aria-controls="nav-links">'
        + '<span class="nav-menu-icon" aria-hidden="true"><span></span><span></span></span>'
        + '<span id="nav-menu-label">Menu</span>'
        + "</button>"
        + '<div class="nav-links" id="nav-links">' + links + "</div>"
        + '<span class="sep">|</span>'
        + '<button id="theme-toggle" onclick="toggleTheme()" class="theme-toggle-btn" aria-label="Toggle dark mode"></button>'
        + "</nav>"
    )


def footer_html(prefix):
    """Brand block (name, tagline, social icons) plus Site and Apps link
    columns, with the copyright on its own ruled-off line. The columns
    collapse to a centered stack on mobile (responsive.css)."""
    def links(items):
        return "".join(
            '<a href="{0}{1}">{2}</a>'.format(prefix, href, label) for href, label in items
        )

    def col(label, items):
        # role="navigation" on a div, not <nav>: the pill nav's styling
        # targets the bare nav element selector site-wide.
        return (
            '<div class="footer-col" role="navigation" aria-label="{0} links">'.format(label)
            + '<h3 class="footer-heading">{0}</h3>'.format(label)
            + links(items)
            + "</div>"
        )

    return (
        "<footer>"
        + '<div class="footer-grid">'
        + '<div class="footer-brand">'
        + '<p class="footer-name">Kevin Struna</p>'
        + '<p class="footer-tagline">Software engineer building Swift &amp; SwiftUI apps for Apple platforms.</p>'
        + '<div class="footer-socials">'
        + '<a href="{0}" target="_blank" rel="noopener noreferrer" aria-label="GitHub">{1}</a>'.format(GITHUB_URL, GITHUB_SVG)
        + '<a href="{0}" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn">{1}</a>'.format(LINKEDIN_URL, LINKEDIN_SVG)
        + '<a href="{0}" target="_blank" rel="noopener noreferrer" aria-label="App Store">{1}</a>'.format(APPSTORE_URL, APPSTORE_SVG)
        + "</div>"
        + "</div>"
        + col("Site", FOOTER_SITE_LINKS)
        + col("Apps", FOOTER_APP_LINKS)
        + "</div>"
        + '<p class="footer-copyright">&copy; 2026 Kevin Struna. All rights reserved.</p>'
        + "</footer>"
    )


# Any local stylesheet/script reference, with or without an existing stamp.
ASSET_REF = re.compile(r'((?:href|src)=")(/?)((?:css|js)/[A-Za-z0-9_.-]+)(?:\?v=[0-9a-f]{8})?(")')


def asset_version(path):
    with open(path, "rb") as f:
        return hashlib.md5(f.read()).hexdigest()[:8]


def stamp_assets(html):
    """Append ?v=<content hash> to every local css/js URL (idempotent)."""
    return ASSET_REF.sub(
        lambda m: "{0}{1}{2}?v={3}{4}".format(
            m.group(1), m.group(2), m.group(3), asset_version(m.group(3)), m.group(4)
        ),
        html,
    )


def replace_block(html, start, end, block, legacy_placeholder=None):
    """Insert the generated block, replacing either the legacy JS-mount
    placeholder (first migration) or a previously generated block (re-runs)."""
    if legacy_placeholder and legacy_placeholder in html:
        return html.replace(legacy_placeholder, block)
    pattern = re.escape(start) + r".*?" + re.escape(end)
    if re.search(pattern, html, flags=re.S):
        return re.sub(pattern, block, html, flags=re.S)
    raise SystemExit("no chrome mount point found (marker or placeholder)")


def main():
    os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
    for path in sorted(glob.glob("*.html")):
        page = os.path.basename(path)
        prefix = URL_PREFIXES.get(page, "")
        with open(path, encoding="utf-8") as f:
            html = f.read()

        head_block = "{0}\n    {1}\n    {2}".format(HEAD_START, head_html(prefix), HEAD_END)
        nav_block = "{0}\n    {1}\n    {2}".format(NAV_START, nav_html(page, prefix), NAV_END)
        foot_block = "{0}\n    {1}\n    {2}".format(FOOT_START, footer_html(prefix), FOOT_END)
        html = replace_block(html, HEAD_START, HEAD_END, head_block)
        html = replace_block(html, NAV_START, NAV_END, nav_block, '<div id="site-nav"></div>')
        html = replace_block(html, FOOT_START, FOOT_END, foot_block, '<div id="site-footer"></div>')

        # Static skip link + focus target (previously added by layout.js).
        if 'class="skip-link"' not in html:
            html = html.replace("<body>", "<body>\n\n    " + SKIP_LINK, 1)
        html = html.replace("<main>", '<main id="main-content" tabindex="-1">', 1)

        html = stamp_assets(html)

        with open(path, "w", encoding="utf-8") as f:
            f.write(html)
        print("synced", page)


if __name__ == "__main__":
    main()
